name: $(Major).$(Minor).$(Patch)
trigger: none
     
variables:
  # Required variables
  appName: 'tailspin-space-game' # Prefix for resource group, site URL, web app, and app service plan
  region: 'West US' # Region for all resources
  dbName: 'tailspindatabase' # Name of database
  serviceConnection: SpaceGame-NonProd # Service connection uses service principal, prod requires approval                        
  wwwrootDir: 'Tailspin.SpaceGame.Web/wwwroot' # web server dir
  storageAccountName: '$(environmentNameLower)spacegamedbstorage2134' # Name of storage account. Must be unique and lowercase.

  # Other variables
  Major: '1'
  Minor: '1'
  Patch: $[counter(format('{0}.{1}', variables['Major'], variables['Minor']), 0)]
  environmentNameLower: ${{ lower(variables['System.StageName'] ) }}
  buildConfiguration: 'Release'
  dotnetSdkVersion: '3.1.100'
  resourceGroup: $(appName)-$(environmentNameLower)-rg
  appServiceName: $(appName)-$(environmentNameLower)-$(appID)
  appServicePlanName: $(appName)-$(environmentNameLower)-service-plan
  sqlServerName: '$(appName)-$(environmentNameLower)-sql'
  SITE_URL: 'https://$(appName)-$(environmentNameLower)-$(appID).azurewebsites.net'  
 
resources:
  repositories:
    - repository: templates 
      type: github
      name: MarcusFelling/Demo.Templates
      endpoint: templates

stages:
- stage: 'Build'
  jobs: 
  - job: 'BuildApp'
    pool:
      vmImage: 'vs2017-win2016'
      demands:
        - npm
        
    steps:
    - task: DotNetCoreInstaller@2
      displayName: 'Use .NET Core SDK $(dotnetSdkVersion)'
      inputs:
        packageType: sdk
        version: '$(dotnetSdkVersion)'
        
    - task: DotNetCoreCLI@2
      displayName: 'Install ReportGenerator'
      inputs:
        command: custom
        custom: tool
        arguments: 'install --global dotnet-reportgenerator-globaltool'
        
    - task: Npm@1
      displayName: 'Run npm install'
      inputs:
        verbose: false

    - script: './node_modules/.bin/node-sass $(wwwrootDir) --output $(wwwrootDir)'
      displayName: 'Compile Sass assets'

    - task: gulp@1
      displayName: 'Run gulp tasks'

    - script: 'echo "$(Build.DefinitionName), $(Build.BuildId), $(Build.BuildNumber)" > buildinfo.txt'
      displayName: 'Write build info'
      workingDirectory: $(wwwrootDir)

    - task: DotNetCoreCLI@2
      displayName: 'Restore project dependencies'
      inputs:
        command: 'restore'
        projects: '**/*.csproj'

    - task: DotNetCoreCLI@2
      displayName: 'Build the project - $(buildConfiguration)'
      inputs:
        command: 'build'
        arguments: '--no-restore --configuration $(buildConfiguration)'
        projects: '**/*.csproj'

    - task: DotNetCoreCLI@2
      displayName: 'Run unit tests - $(buildConfiguration)'
      inputs:
        command: 'test'
        arguments: '--no-build --configuration $(buildConfiguration) /p:CollectCoverage=true /p:CoverletOutputFormat=cobertura /p:CoverletOutput=$(Build.SourcesDirectory)/TestResults/Coverage/'
        publishTestResults: true
        projects: '**/*.Tests.csproj'
        testRunTitle: 'Unit Tests'

    - script: |
        reportgenerator -reports:$(Build.SourcesDirectory)/**/coverage.cobertura.xml -targetdir:$(Build.SourcesDirectory)/CodeCoverage -reporttypes:HtmlInline_AzurePipelines
      displayName: 'Create code coverage report'

    - task: PublishCodeCoverageResults@1
      displayName: 'Publish code coverage report'
      inputs:
        codeCoverageTool: 'cobertura'
        summaryFileLocation: '$(Build.SourcesDirectory)/**/coverage.cobertura.xml'

    - task: DotNetCoreCLI@2
      displayName: 'Publish the project - $(buildConfiguration)'
      inputs:
        command: 'publish'
        projects: '**/Tailspin.SpaceGame.Web.csproj'
        publishWebProjects: false
        arguments: '--no-build --configuration $(buildConfiguration) --output $(Build.ArtifactStagingDirectory)/$(buildConfiguration)'
        zipAfterPublish: true

    - publish: '$(Build.ArtifactStagingDirectory)'
      artifact: dropApp

  - job: BuildDacpac
    pool:
      vmImage: 'windows-2019'
    steps:
    - task: DotNetCoreCLI@2
      displayName: 'Restore project dependencies'
      inputs:
        command: 'restore'
        projects: '**/*.csproj'

    - task: VSBuild@1
      displayName: 'Build the database project'
      inputs:
        project: '**/*.sqlproj'

    - task: CopyFiles@2
      displayName: 'Copy dacpac file to staging directory'
      inputs:
        contents: |
          Tailspin.SpaceGame.Database/bin/**/*.dacpac
        targetFolder: '$(Build.StagingDirectory)'

    - task: PublishBuildArtifacts@1
      displayName: 'Publish Artifact'
      inputs:
        pathToPublish: '$(Build.ArtifactStagingDirectory)'
        artifactName: dropDacpac
      condition: succeededOrFailed()

  - job: BuildBicep
    pool:
      vmImage: 'ubuntu-20.04'
    steps:
    - script: |
        # Fetch the latest Bicep CLI binary
        curl -Lo bicep https://github.com/Azure/bicep/releases/latest/download/bicep-linux-x64
        # Mark it as executable
        chmod +x ./bicep
        # Add bicep to your PATH (requires admin)
        sudo mv ./bicep /usr/local/bin/bicep
        # Verify you can now access the 'bicep' command
        bicep --help
        # Done!
      displayName: 'Install Bicep'
      
    - script: |
        bicep build Tailspin.SpaceGame.Bicep/main.bicep
      displayName: 'Run Bicep Build'      

    - task: CopyFiles@2
      displayName: 'Copy ARM Template (.json) files to staging directory'
      inputs:
        contents: |
          Tailspin.SpaceGame.Bicep/**/*.json
        targetFolder: '$(Build.StagingDirectory)'

    - task: PublishBuildArtifacts@1
      displayName: 'Publish Artifact' 
      inputs:
        pathToPublish: '$(Build.ArtifactStagingDirectory)'
        artifactName: dropARM
      condition: succeededOrFailed()

- stage: 'Dev'
  displayName: 'Deploy to the dev environment'
  dependsOn:
  - Build 
  condition: succeeded('Build')
  jobs:
  - deployment: Deploy
    pool:
      vmImage: 'windows-2019'
    environment: dev
    variables:
    - group: SpaceGame
    - name: appID
      value: $(Build.BuildId)    
    strategy:
      runOnce:
        deploy:
          steps:
          - template: spacegame-bicep-deploy.yml@templates

  - job: DBSchemaApproval
    dependsOn: Deploy
    condition: eq(variables['schemaChanged'], True)
    pool: server
    variables:
    - group: SpaceGame     
    steps:
    - task: ManualValidation@0
      inputs:
        notifyUsers: 'mafellin@microsoft.com'
        instructions: 'DBA approval required for schema change'
    
  - deployment: DeployDBSchema
    dependsOn: 
    - Deploy
    - DBSchemaApproval
    condition: |
      and
      (
        succeeded('Deploy'),
        in(dependencies.DBSchemaApproval.result, 'Succeeded', 'Skipped')
      )     
    pool:
      vmImage: 'windows-2019'
    environment: dev
    variables:
    - group: SpaceGame
    strategy:
      runOnce:
        deploy:
          steps:    
          - download: current
            artifact: dropDacpac            
          - task: SqlAzureDacpacDeployment@1
            displayName: 'Deploy SQL schema'
            inputs:
              azureSubscription: '$(serviceConnection)'
              authenticationType: 'server'
              serverName: '$(sqlServerName).database.windows.net'
              databaseName: '$(dbName)'
              sqlUsername: '$(adminlogin)'
              sqlPassword: '$(adminPassword)'
              deployType: 'DacpacTask'
              deploymentAction: 'Publish'
              dacpacFile: '$(Pipeline.Workspace)/dropDacpac/Tailspin.SpaceGame.Database/bin/Debug/Tailspin.SpaceGame.Database.dacpac'
              ipDetectionMethod: 'AutoDetect'
          - task: PowerShell@2
            displayName: 'Remove "schemaChanged" pipeline variable'
            inputs:
              targetType: 'inline'
              script: | 
                Install-Module VSTeam -Scope CurrentUser -Force
                Set-VSTeamAccount –Account $(System.CollectionUri) -PersonalAccessToken $(PAT)
                $methodParameters = @{
                  ProjectName = "$(System.TeamProject)"
                  Name = "SpaceGame"}
                $vg = Get-VSTeamVariableGroup  @methodParameters 
                $vars = @{}
                $vg.variables | Get-Member -MemberType *Property | %{$vars.($_.Name) = $vg.variables.($_.Name)}
                $vars.Remove("schemaChanged")
                $methodParameters = @{
                  id = $vg.id
                  ProjectName = "$(System.TeamProject)"
                  Name = "SpaceGame"
                  Description = ""
                  Type = "Vsts"
                  Variables = $vars}
                Update-VSTeamVariableGroup @methodParameters

  - job: ReviewApp
    dependsOn: 
    - DeployDBSchema
    condition: succeeded('DeployDBSchema')
    pool: 
      vmImage: 'ubuntu-20.04'
    variables:
    - group: SpaceGame     
    steps:
    - task: GitHubComment@0
      displayName: 'Add PR comment with site url'  
      inputs:
        gitHubConnection: 'MarcusFelling'
        repositoryName: '$(Build.Repository.Name)'
        comment: 'The new app is ready for testing: $(SITE_URL)' 

- stage: 'Test'
  displayName: 'Deploy to the test environment'
  dependsOn:
  - Dev
  jobs:
  - deployment: Deploy
    pool:
      vmImage: 'windows-2019'
    environment: test
    variables:      
    - group: SpaceGame
    - name: appID
      value: '26178'  
    strategy:
      runOnce:
        deploy:
          steps:
          - template: spacegame-bicep-deploy.yml@templates

  - job: DBSchemaApproval
    dependsOn: Deploy
    condition: eq(variables['schemaChanged'], True)
    pool: server
    variables:
    - group: SpaceGame     
    steps:
    - task: ManualValidation@0
      inputs:
        notifyUsers: 'mafellin@microsoft.com'
        instructions: 'DBA approval required for schema change'
    
  - deployment: DeployDBSchema
    dependsOn: 
    - Deploy
    - DBSchemaApproval
    condition: |
      and
      (
        succeeded('Deploy'),
        in(dependencies.DBSchemaApproval.result, 'Succeeded', 'Skipped')
      )     
    pool:
      vmImage: 'windows-2019'
    environment: test
    variables:
    - group: SpaceGame
    strategy:
      runOnce:
        deploy:
          steps:    
          - download: current
            artifact: dropDacpac            
          - task: SqlAzureDacpacDeployment@1
            displayName: 'Deploy SQL schema'
            inputs:
              azureSubscription: '$(serviceConnection)'
              authenticationType: 'server'
              serverName: '$(sqlServerName).database.windows.net'
              databaseName: '$(dbName)'
              sqlUsername: '$(adminlogin)'
              sqlPassword: '$(adminPassword)'
              deployType: 'DacpacTask'
              deploymentAction: 'Publish'
              dacpacFile: '$(Pipeline.Workspace)/dropDacpac/Tailspin.SpaceGame.Database/bin/Debug/Tailspin.SpaceGame.Database.dacpac'
              ipDetectionMethod: 'AutoDetect'
          - task: PowerShell@2
            displayName: 'Remove "schemaChanged" pipeline variable'
            inputs:
              targetType: 'inline'
              script: | 
                Install-Module VSTeam -Scope CurrentUser -Force
                Set-VSTeamAccount –Account $(System.CollectionUri) -PersonalAccessToken $(PAT)
                $methodParameters = @{
                  ProjectName = "$(System.TeamProject)"
                  Name = "SpaceGame"}
                $vg = Get-VSTeamVariableGroup  @methodParameters 
                $vars = @{}
                $vg.variables | Get-Member -MemberType *Property | %{$vars.($_.Name) = $vg.variables.($_.Name)}
                $vars.Remove("schemaChanged")
                $methodParameters = @{
                  id = $vg.id
                  ProjectName = "$(System.TeamProject)"
                  Name = "SpaceGame"
                  Description = ""
                  Type = "Vsts"
                  Variables = $vars}
                Update-VSTeamVariableGroup @methodParameters

  - job: RunUITests
    dependsOn: Deploy
    displayName: 'Run UI tests'
    pool:
      vmImage: 'vs2017-win2016'
    variables:    
    - group: SpaceGame
    steps:
    - template: functional-tests.yml@templates

  - job: RunLoadTests
    dependsOn: Deploy
    displayName: 'Run load tests'
    pool:
      vmImage: 'ubuntu-20.04'
    variables:
      jmeterVersion: '5.2'
    steps: 
    - template: load-tests.yml@templates

- stage: 'Prod' 
  displayName: 'Deploy to the Production environment'
  dependsOn: Test
  condition: succeeded('Test')
  jobs:
  - deployment: Deploy
    pool:
      vmImage: 'windows-2019'
    environment: prod
    variables:
    - group: SpaceGame
    - name:  serviceConnection
      value: SpaceGame-Prod
    - name: appID
      value: '26178' 
    strategy:
      runOnce:
        deploy:
          steps:
          - template: spacegame-bicep-deploy.yml@templates

  - job: DBSchemaApproval
    dependsOn: Deploy
    condition: eq(variables['schemaChanged'], True)
    pool: server
    variables:
    - group: SpaceGame     
    steps:
    - task: ManualValidation@0
      inputs:
        notifyUsers: 'mafellin@microsoft.com'
        instructions: 'DBA approval required for schema change'
    
  - deployment: DeployDBSchema
    dependsOn: 
    - Deploy
    - DBSchemaApproval
    condition: |
      and
      (
        succeeded('Deploy'),
        in(dependencies.DBSchemaApproval.result, 'Succeeded', 'Skipped')
      )     
    pool:
      vmImage: 'windows-2019'
    environment: prod
    variables:
    - group: SpaceGame
    strategy:
      runOnce:
        deploy:
          steps:    
          - download: current
            artifact: dropDacpac            
          - task: SqlAzureDacpacDeployment@1
            displayName: 'Deploy SQL schema'
            inputs:
              azureSubscription: '$(serviceConnection)'
              authenticationType: 'server'
              serverName: '$(sqlServerName).database.windows.net'
              databaseName: '$(dbName)'
              sqlUsername: '$(adminlogin)'
              sqlPassword: '$(adminPassword)'
              deployType: 'DacpacTask'
              deploymentAction: 'Publish'
              dacpacFile: '$(Pipeline.Workspace)/dropDacpac/Tailspin.SpaceGame.Database/bin/Debug/Tailspin.SpaceGame.Database.dacpac'
              ipDetectionMethod: 'AutoDetect'
          - task: PowerShell@2
            displayName: 'Remove "schemaChanged" pipeline variable'
            inputs:
              targetType: 'inline'
              script: | 
                Install-Module VSTeam -Scope CurrentUser -Force
                Set-VSTeamAccount –Account $(System.CollectionUri) -PersonalAccessToken $(PAT)
                $methodParameters = @{
                  ProjectName = "$(System.TeamProject)"
                  Name = "SpaceGame"}
                $vg = Get-VSTeamVariableGroup  @methodParameters 
                $vars = @{}
                $vg.variables | Get-Member -MemberType *Property | %{$vars.($_.Name) = $vg.variables.($_.Name)}
                $vars.Remove("schemaChanged")
                $methodParameters = @{
                  id = $vg.id
                  ProjectName = "$(System.TeamProject)"
                  Name = "SpaceGame"
                  Description = ""
                  Type = "Vsts"
                  Variables = $vars}
                Update-VSTeamVariableGroup @methodParameters

- stage: 'Cleanup'
  displayName: 'Cleanup dev environment'
  condition: or(failed(), succeeded('Prod'))
  jobs:
  - deployment: Deploy
    pool:
      vmImage: 'windows-2019'
    environment: dev 
    variables:
    - group: SpaceGame
    - name: appID
      value: $(Build.BuildId)    
    strategy:
      runOnce: 
        deploy:
          steps:
          - task: AzureCLI@2
            inputs:
                azureSubscription: $(serviceConnection)
                scriptType: 'pscore'
                scriptLocation: 'inlineScript'
                inlineScript: 'az webapp delete --name $(appName)-Dev-$(appID) --yes'